title = "Config file for the keithley plugin using a 7708 acquisition card"
termination_character = "Keithley must be set to LF"

[INSTRUMENT]
rsrc_name = ""

panel = ""

[MODULE]
module_name = 7706

[CHANNELS]
101 = {}
102 = {}
103 = {}
104 = {}
105 = {}
106 = {}
107 = {}
108 = {}
109 = {}
110 = {}
111 = {}
112 = {}
113 = {}
114 = {}
115 = {}
116 = {}
117 = {}
118 = {}
119 = {}
120 = {}