title = "Config file for the keithley plugin using a 7708 acquisition card"

[INSTRUMENT]
rsrc_name = ""
termination = ""
panel = ""

[MODULE]
module_name = 7708

[CHANNELS]
101 = {}
102 = {}
103 = {}
104 = {}
105 = {}
106 = {}
107 = {}
108 = {}
109 = {}
110 = {}
111 = {}
112 = {}
113 = {}
114 = {}
115 = {}
116 = {}
117 = {}
118 = {}
119 = {}
120 = {}
121 = {}
122 = {}
123 = {}
124 = {}
125 = {}
126 = {}
127 = {}
128 = {}
129 = {}
130 = {}
131 = {}
132 = {}
133 = {}
134 = {}
135 = {}
136 = {}
137 = {}
138 = {}
139 = {}
140 = {}