title = "Config file for the keithley2700 plugin using a 7706 acquisition card"

[INSTRUMENT]
rsrc_name = "ASRL1::INSTR"  # resource name
termination = "LF"  # termination character
panel = "REAR" # Front/rear panel

[SAVING_TXT_DATA]
path = ""

[MODULE]
module_name = 7706

[CHANNELS]
101 = {}
102 = {}
103 = {}
104 = {}
105 = {}
106 = {}
107 = {}
108 = {}
109 = {}
110 = {}
111 = {}
112 = {}
113 = {}
114 = {}
115 = {}
116 = {}
117 = {}
118 = {}
119 = {}
120 = {}